# --- ARQUIVO SECRETO DE DESENVOLVIMENTO (NAO COMMITAR) ---

# Banco de Dados do PC do SENAI
spring.datasource.url=jdbc:mysql://localhost:3306/stockbot
spring.datasource.username=root
spring.datasource.password=aluno

# Token JWT (Cole aquela senha gigante que geramos)
api.security.token.secret=c9301dc80b2ed16337b16a8e743813486354a27afb55a40bd081c184596cbe8b975b580a79077b7d58911cbb2451b83eea32813c12ddd11ee49b4cfddcaf04d9

# E-mail (Suas credenciais reais)
spring.mail.username=stockbotdevstest@gmail.com
spring.mail.password=rolhvpasmlllfues